apiVersion: v1
kind: Service
metadata:
  name: {{ include "nsi-requester.fullname" . }}
  labels:
    {{- include "nsi-requester.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if eq .Values.service.type "LoadBalancer" }}
  externalTrafficPolicy: Local
  loadBalancerIP: {{ .Values.service.ipAddress }}
{{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "nsi-requester.selectorLabels" . | nindent 4 }}
